In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

### напишіть функцію гіпотези лінійної регресії у векторному вигляді;

In [5]:
def hyp(w, x):
    return w[0] + w[1] * x

w = np.array([3, 1])
x = np.array([2, 5])
res = hyp(w, x)
print("Результат гіпотези:", res)

Результат гіпотези: [5 8]


### створіть функцію для обчислення функції втрат у векторному вигляді;

In [6]:
def mean_squared_error(w, x, y):
    lnx = len(x)
    predictions = hyp(w, x)
    mse = np.sum((predictions - y)**2) / lnx
    return mse

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 5])

w = np.array([0.0, 0.0])

loss = mean_squared_error(w, x, y)

print("Функція втрат MSE:", loss)

Функція втрат MSE: 17.2


### реалізуйте один крок градієнтного спуску;

In [7]:
def gradient_descent_step(w, x, y, learning_rate):
    lnx = len(x)

    gradient_w0 = (1/lnx) * np.sum(hyp(w, x) - y)
    gradient_w1 = (1/lnx) * np.sum((hyp(w, x) - y) * x)

    w[0] -= learning_rate * gradient_w0
    w[1] -= learning_rate * gradient_w1

    return w


x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 5])


w = np.array([0.0, 0.0])

learning_rate = 0.01
w = gradient_descent_step(w, x, y, learning_rate)

print("Оновлені ваги:", w)

Оновлені ваги: [0.04  0.132]


### знайдіть найкращі параметри $\vec{w}$ для датасету прогнозуючу ціну на будинок залежно від площі, кількості ванних кімнат та кількості спалень;

In [9]:
df = pd.read_csv('/Housing.csv')
df.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [10]:
X = df[['area', 'bedrooms', 'bathrooms']]
y = df['price']

model = LinearRegression()
model.fit(X, y)

w = model.coef_
w

array([3.78762754e+02, 4.06820034e+05, 1.38604950e+06])

### знайдіть ці ж параметри за допомогою аналітичного рішення;

In [12]:
X = df[['area', 'bedrooms', 'bathrooms']]
y = df['price']

X = X.copy()
X['bias'] = 1

w1 = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
w1 = w1[:-1]

w1

array([3.78762754e+02, 4.06820034e+05, 1.38604950e+06])

порівняйте отримані результати.

In [14]:
w == w1

array([False, False, False])